[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "rue"
version = "0.1"
requires-python = ">= 3.9"
description = "RethinkDB queue system"
dependencies = ["rethinkdb"]

